#!/bin/bash

BUCKETNAME=
KEYFILE=
LOGSERVER=

while getopts "b:k:l:" opt; do
    case $opt in
	b) # set S3 bucket name
	    if [[ -n $OPTARG ]]; then
		BUCKETNAME=$OPTARG
	    fi;;
	k) # set KEYFILE
	    if [[ -e $OPTARG ]]; then
		KEYFILE=$OPTARG
	    else
		echo "Key file at '$OPTARG' does not exist."
	    fi;;
	l) # set LOGSERVER
	    if [[ -n $OPTARG ]]; then
		LOGSERVER=$OPTARG
	    fi;;
	\?)
	    echo "Got invalid option '$OPTARG'. Exiting."
	    exit;;
    esac
done

# Ensure we got a key file
if [[ -z $KEYFILE ]]; then
    echo "Got no keyfile. Exiting."
    exit
fi

echo "KEYFILE: $KEYFILE"
echo "BUCKETNAME: $BUCKETNAME"
echo "LOGSERVER: $LOGSERVER"

# shift option index to positional arguments
shift $((OPTIND - 1))

archivename="backup-$(date +%Y-%M-%dT%Hh%Mm%Ss%Z).tar.gz"

echo "Archiving and encrypting '$1' as '$archivename'..."

tar czf - $1 | gpg --batch --passphrase-file $KEYFILE -c -o ${archivename}.gpg

echo "Successfully created ${archivename}.gpg"

if [[ -n $BUCKETNAME ]]; then
    echo "Uploading encrypted archive to S3 Bucket '$BUCKETNAME'..."
    aws s3 cp "${archivename}.gpg" "s3://${BUCKETNAME}"
fi

if [[ -n $LOGSERVER ]]; then
    echo "Logging backup to remote server '$LOGSERVER'..."
    LOGMSG="bash-backup: successfully copied archive '${archivename}' to S3 Bucket '${BUCKETNAME}'"
    echo $LOGMSG | logger -n $LOGSERVER
fi

echo "Upload successful!"

