#!/bin/bash

BUCKETNAME=
KEYFILE=
LOGSERVER=

while getopts "b:k:l:" opt; do
    case $opt in
	b) # set S3 bucket name
	    if [[ -n $OPTARG ]]; then
		BUCKETNAME=$OPTARG
	    fi;;
	k) # set KEYFILE
	    if [[ -e $OPTARG ]]; then
		KEYFILE=$OPTARG
	    else
		echo "Key file at '$OPTARG' does not exist."
	    fi;;
	l) # set LOGSERVER
	    if [[ -n $OPTARG ]]; then
		LOGSERVER=$OPTARG
	    fi;;
	\?)
	    echo "Got invalid option '$OPTARG'. Exiting."
	    exit;;
    esac
done

# Ensure we got a key file
if [[ -z $KEYFILE ]]; then
    echo "Got no keyfile. Exiting."
    exit
fi

# shift option index to positional arguments
shift $((OPTIND - 1))

archivename="backup-$(date +%Y-%M-%dT%Hh%Mm%Ss%Z).tar.gz"

echo "Archiving and encrypting '$1' as '$archivename'..."

tar czf - $1 | gpg --batch --passphrase-file $KEYFILE -c -o ${archivename}.gpg

echo "Successfully created ${archivename}.gpg"

S3UPLOAD=
if [[ -n $BUCKETNAME ]]; then
    echo "Uploading encrypted archive to S3 Bucket '$BUCKETNAME'..."
    aws s3 cp "${archivename}.gpg" "s3://${BUCKETNAME}"
    S3UPLOAD=$?
fi

# If user specified a log server, log success or failure of S3 upload.
if [[ -n $LOGSERVER && -n $BUCKETNAME ]]; then
    if [[ $S3UPLOAD -ne 0 ]]; then # S3 Upload failed
	logger -t bash-backup -n $LOGSERVER "bash-backup created archive '${archivename}' but failed to upload to S3."
    else                           # S3 Upload succeeded
	logger -t bash-backup -n $LOGSERVER "bash-backup created archive '${archivename}' and uploaded to S3 Bucket '${BUCKETNAME}'."
    fi
fi

