#!/bin/bash

BUCKETNAME=
KEYFILE=

while getopts "b:k:" opt; do
    case $opt in
	b) # set S3 bucket name
	    if [[ -n $OPTARG ]]; then
		echo "BUCKETNAME: $OPTARG"
		BUCKETNAME=$OPTARG
	    fi;;
	k) # set KEYFILE
	    if [[ -e $OPTARG ]]; then
		echo "KEYFILE: $OPTARG"
		KEYFILE=$OPTARG
	    else
		echo "Key file at '$OPTARG' does not exist."
	    fi;;
	\?)
	    echo "Got invalid option '$OPTARG'. Exiting."
	    exit;;
    esac
done

# Ensure we got a key file
if [[ -z $KEYFILE ]]; then
    echo "Got no keyfile. Exiting."
    exit
fi

# shift option index to positional arguments
shift $((OPTIND - 1))

archivename="backup-$(date +%Y-%M-%dT%Hh%Mm%Ss%Z).tar.gz"

echo "Archiving and encrypting '$1' as '$archivename'..."

tar czf - $1 | gpg --batch --passphrase-file ./keytest.key -c -o ${archivename}.gpg

echo "Successfully created ${archivename}.gpg"

if [[ -z $BUCKETNAME ]]; then
    echo "No S3 Bucket provided; skipping upload."
    exit;
fi

echo "Uploading encrypted archive to S3 Bucket '$BUCKETNAME'..."

aws s3 cp "${archivename}.gpg" "s3://${BUCKETNAME}"

echo "Upload successful!"

